#cloud-config
merge_how: dict(recurse_array)+list(append)
write_files:
  - path: /etc/sysconfig/heat-params
    owner: "root:root"
    permissions: "0644"
    content: |
      WAIT_HANDLE="$WAIT_HANDLE"
      HTTP_PROXY="$HTTP_PROXY"
      HTTPS_PROXY="$HTTPS_PROXY"
      NO_PROXY="$NO_PROXY"
      FIXED_NETWORK_CIDR="$FIXED_NETWORK_CIDR"
      SWARM_MASTER_IP="$SWARM_MASTER_IP"
      SWARM_NODE_IP="$NODE_IP"
